require 'outright_cap/recipes/apt'
require 'outright_cap/recipes/sqs'
require 'outright_cap/recipes/unicorn'
require 'outright_cap/recipes/workling'
require 'outright_cap/recipes/nginx'
require 'outright_cap/recipes/thrift'
